// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5VWZG8VJ2IqQCGH1XnoFgEwzkSRdjO-4',
    appId: '1:624671355101:web:c4e76c29397a65c42b6b34',
    messagingSenderId: '624671355101',
    projectId: 'newsapp-74a39',
    authDomain: 'newsapp-74a39.firebaseapp.com',
    storageBucket: 'newsapp-74a39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFgY5aG5FXK_crXIDCmN5vXNNp3xJzKw',
    appId: '1:624671355101:android:6778d29b1688e1a52b6b34',
    messagingSenderId: '624671355101',
    projectId: 'newsapp-74a39',
    storageBucket: 'newsapp-74a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASgSp4YX_RxfdUtz-yA3ziBbVVmEnjXyk',
    appId: '1:624671355101:ios:a5b362908f0065502b6b34',
    messagingSenderId: '624671355101',
    projectId: 'newsapp-74a39',
    storageBucket: 'newsapp-74a39.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASgSp4YX_RxfdUtz-yA3ziBbVVmEnjXyk',
    appId: '1:624671355101:ios:a5b362908f0065502b6b34',
    messagingSenderId: '624671355101',
    projectId: 'newsapp-74a39',
    storageBucket: 'newsapp-74a39.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5VWZG8VJ2IqQCGH1XnoFgEwzkSRdjO-4',
    appId: '1:624671355101:web:8f9b9fa28d6d7c502b6b34',
    messagingSenderId: '624671355101',
    projectId: 'newsapp-74a39',
    authDomain: 'newsapp-74a39.firebaseapp.com',
    storageBucket: 'newsapp-74a39.appspot.com',
  );
}
